name: ci

on:
  push:
    branches: ["master", "dev", "rework"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest, # x86_64
          ubuntu-24.04-arm, # arm
          macos-latest, # arm
          windows-latest, # x86_64
        ]
    env:
      CARGO_TARGET_DIR: target
      RUST_LIB_PATH: target/debug

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2

      - if: runner.os == 'Linux'
        name: Run docs lint
        run: deno doc --lint mod.ts

      - name: Run tests
        run: deno task test
